---
# 복수 대상 선택
- name: mini
  # 대상 (~/.ansible/hosts)
  hosts: mini
  # sudo 사용
  become: true
  # become_user: crom
  # 변수 선언
  vars:
    file: 'memo.txt'
  # 변수 외부 파일로 받기
  vars_files: ~/vars_files_zzizily
  # 변수를 입력 받기
  vars_prompt:
    # 변수명
    - name: 'password'
      prompt: 'https password input plz!!!'
      private: yes
  tasks:
    - name: debug test
      debug:
        msg: 'var key={{key}}, file={{file}}, password={{password}}'
    - name: shell test
      shell: |
        echo {{key}} >> {{file}}
        echo {{password}} >> {{file}}
    - name: manage tools
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - vim
        - neofetch
        - glances
        - netcat
        - curl
        - git
    #- name: openjdk-8-jdk install
    #  apt:
    #    name: openjdk-8-jdk

- name: raspberrypi
  # 대상 (~/.ansible/hosts)
  hosts: raspberrypi
  # sudo 사용
  become: true
  #become_user: pi
  tasks:
    - name: manage tools
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - vim
        - neofetch
        - glances
        - netcat
        - curl
        - git
